### ISSUE TITLE
动态链库文件不全 无法运行

### ISSUE THREAD

**Issue by RaphealK** [Blackstacker/autodrive_demo_user#1]
erros：
   from socket_config import *
ImportError: DLL load failed while importing socket_config: 找不到指定的模块。
通过分析pyd文件可以发现一大堆依赖库确实，自己补全太麻烦了，请一并上传
<img width="960" alt="luk2gm0l 2kj" src="https://github.com/Blackstacker/autodrive_demo_user/assets/24764156/4d94bcc9-d6e5-4473-a2cb-4b3c362041e6">

**Comment by Blackstacker** [comment]
使用的是32位的win系统吗？

**Comment by Blackstacker** [comment]
后续我补充一个系统版本与python版本，pyd对系统与python版本都有一定的要求

**Comment by RaphealK** [comment]
系统版本：win10-LTSC-64位
Python版本：3.1-3.10都测试过

**Comment by RaphealK** [comment]
我解决了，重新安装了一个干净的Python3.9的环境，main能运行了
